name: BigDuck_SkinTwin

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}     # IP ของ Server คุณ
          username: ${{ secrets.SERVER_USER }} # Username (เช่น root หรือ ubuntu)
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH Key สำหรับเข้า Server
          script: |
            cd /path/to/your/CPE444            
            git pull origin main          
            docker-compose up -d           
